export const ErrorCodes ={
    INVALID_INPUT: 'ERR_INVALID_INPUT',
    INVALID_FIELD_LENGTH: 'ERR_INVALID_FIELD_LENGTH',
    NOT_FOUND: 'ERR_NOT_FOUND',
    UNAUTHORIZED: 'ERR_UNAUTHORIZED',
    SERVER_ERROR: 'ERR_SERVER_ERROR',
    TIMEOUT: 'ERR_TIMEOUT',

}
