import { authService } from "./auth.service";
import { filesService } from "./files.service";
import { mailService } from "./mail.service";
import { postsService } from "./posts.service";
import { usersService } from "./users.service";
import { likesService } from "./likes.service";
import { commentsService } from "./comments.service";
import { viewsService } from "./views.service";
import { repostsService } from "./reposts.service";
export { authService, usersService, filesService, mailService, postsService, likesService, commentsService, viewsService, repostsService };
